### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by optimaldoe** [cubiclesoft/cloud-storage-server#1]
It would be most welcome to state that a database should be installed. I ended stuck with the lack of MariaDB.  Now having installed MariaDb I discover it does even not accpt mariadb?

**Comment by cubiclesoft** [comment]
Cloud Storage Server uses SQLite and needs the PHP PDO SQLite module to be enabled and/or installed.  I can see how that might be confusing since I mention a product that includes Maria DB.

The installer for Cloud Storage Server is...awkward.  It was written long before the question-answer CLI tools that I build today existed.  It also assumes that it will be Internet-facing so it generates SSL/TLS certificates, both of which were probably bad design decisions.  It's also kind of a weird, general-purpose API server that I kind of went overkill on with `/scripts` and `/feeds`.  `/files` is fine if still a tad overkill.

Updated the documentation to indicate SQLite is required.
